### ISSUE TITLE
[ENH] Calculate signed difference between two angles

### ISSUE THREAD

**Issue by mbeyeler** [pulse2percept/pulse2percept#296]
Add a utility function that calculates the signed difference between two angles.

**Comment by Conrad-Crowley** [comment]
Is this issue still open? If so, I'd like to implement it.

**Comment by Conrad-Crowley** [comment]
@mbeyeler Should the function raise an exception if `source_angle` or `target_angle `is not in the interval `[0,hi]`? 

Suppose this was called by a user who didn't read the function docs:
`delta_angle(4*np.pi, np.pi, np.pi/2)`
this returns `8.881784197001252e-16` as opposed to the expected 0. This is due to the modulo operation on floats.

Raising these exceptions would remove the possibility of using a nested `delta_angle(delta_angle(x,y),z)` as you'd need to ensure `delta_angle(x,y)` is positive beforehand.

I understand these are unlikely use cases but I would like to know if I should raise the exceptions

**Comment by mbeyeler** [comment]
It's good you're thinking through the edge cases! I would add this case to the test function, but not raise an exception: `8.881784197001252e-16` is really close to 0, so the function behaves as expected. If you add an `npt.assert_almost_equal(delta_angle(4*np.pi, np.pi, np.pi/2), 0)` statement, the test should pass.
